### ISSUE TITLE
Crash when changing resolution

### ISSUE THREAD

**Issue by a1exsh** [ihhub/fheroes2#4105]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Changing game resolution often results in a crash, e.g. `Segmentation fault` or different assertions in `malloc.c`.

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f41caf07537 in __GI_abort () at abort.c:79
#2  0x00007f41caf60768 in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7f41cb06ee2d "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f41caf67a5a in malloc_printerr
    (str=str@entry=0x7f41cb071230 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007f41caf6909c in _int_free
    (av=0x7f41cb0a0b80 <main_arena>, p=0x5641dedbd300, have_lock=<optimized out>) at malloc.c:4317
#5  0x00007f41cb4e53ef in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#6  0x00007f41cb51eb8c in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#7  0x00005641dd255497 in (anonymous namespace)::RenderEngine::clear() (this=0x5641ddd13790)
    at screen.cpp:824
#8  0x00005641dd256043 in fheroes2::Display::resize(int, int) (this=
    0x5641dd3f8ca0 <fheroes2::Display::instance()::display>, width_=3840, height_=2160)
    at screen.cpp:1246
#9  0x00005641dd0dadd3 in Dialog::SelectResolution() ()
    at ../fheroes2/dialog/dialog_resolution.cpp:202
#10 0x00005641dd0c1ca6 in fheroes2::openGameSettings() ()
    at ../fheroes2/dialog/dialog_game_settings.cpp:200
#11 0x00005641dd11ad84 in Game::MainMenu(bool) (isFirstGameRun=false)
    at ../fheroes2/game/game_mainmenu.cpp:300
#12 0x00005641dd119aae in Game::mainGameLoop(bool) (isFirstGameRun=false)
    at ../fheroes2/game/game_mainmenu.cpp:73
#13 0x00005641dd100462 in main(int, char**) (argc=1, argv=0x7fffd012da68)
    at ../fheroes2/game/fheroes2.cpp:214
(gdb) 
```

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f578747e537 in __GI_abort () at abort.c:79
#2  0x00007f57874d7768 in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7f57875e5e2d "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f57874dea5a in malloc_printerr
    (str=str@entry=0x7f57875e85c0 "malloc(): smallbin double linked list corrupted")
    at malloc.c:5347
#4  0x00007f57874e1fb4 in _int_malloc
    (av=av@entry=0x7f5787617b80 <main_arena>, bytes=bytes@entry=48) at malloc.c:3644
#5  0x00007f57874e3ed1 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>)
    at malloc.c:3428
#6  0x00007f5787a3f342 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#7  0x00007f5787a127af in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#8  0x00007f5787a12a85 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#9  0x00007f5787a12c53 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#10 0x00007f5787a18835 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#11 0x00007f5787a1898b in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#12 0x0000555f1b4bd945 in (anonymous namespace)::RenderEngine::render(fheroes2::Display const&, fheroes2::RectBase2D<int, int> const&) ()
#13 0x0000555f1b4be96a in fheroes2::Display::_renderFrame(fheroes2::RectBase2D<int, int> const&) const ()
#14 0x0000555f1b4be7cc in fheroes2::Display::render(fheroes2::RectBase2D<int, int> const&) ()
#15 0x0000555f1b4be423 in fheroes2::Display::render() ()
#16 0x0000555f1b350073 in (anonymous namespace)::showConfigurationWindow() ()
#17 0x0000555f1b350903 in fheroes2::openGameSettings() ()
#18 0x0000555f1b3a9a20 in Game::MainMenu(bool) ()
#19 0x0000555f1b3a874a in Game::mainGameLoop(bool) ()
#20 0x0000555f1b39004d in main ()
```

```
#0  0x0000563b4f6c8577 in (anonymous namespace)::BaseSDLRenderer::copyImageToSurface(fheroes2::Image const&, SDL_Surface*, fheroes2::Rect const&)
    (this=0x563b50dc67a0, image=..., surface=0x563b515372e0, roi=...) at screen.cpp:238
#1  0x0000563b4f6d178f in (anonymous namespace)::RenderEngine::render(fheroes2::Display const&, fheroes2::Rect const&) (this=0x563b50dc6790, display=..., roi=...) at screen.cpp:836
#2  0x0000563b4f6dd24a in fheroes2::Display::_renderFrame(fheroes2::RectBase2D<int, int> const&) const (this=0x563b501d1980 <fheroes2::Display::instance()::display>, roi=...) at screen.cpp:1331
#3  0x0000563b4f6dc101 in fheroes2::Display::render(fheroes2::RectBase2D<int, int> const&)
    (this=0x563b501d1980 <fheroes2::Display::instance()::display>, roi=...) at screen.cpp:1303
#4  0x0000563b4f6d9ca9 in fheroes2::Display::render()
    (this=0x563b501d1980 <fheroes2::Display::instance()::display>) at screen.cpp:1269
#5  0x0000563b4f072497 in (anonymous namespace)::showConfigurationWindow() ()
    at ../fheroes2/dialog/dialog_game_settings.cpp:135
#6  0x0000563b4f073acc in fheroes2::openGameSettings() ()
    at ../fheroes2/dialog/dialog_game_settings.cpp:197
#7  0x0000563b4f1f2cc3 in Game::MainMenu(bool) (isFirstGameRun=false)
    at ../fheroes2/game/game_mainmenu.cpp:300
#8  0x0000563b4f1ef062 in Game::mainGameLoop(bool) (isFirstGameRun=false)
    at ../fheroes2/game/game_mainmenu.cpp:73
#9  0x0000563b4f182aff in main(int, char**) (argc=1, argv=0x7ffd774080c8)
    at ../fheroes2/game/fheroes2.cpp:214
```

Sometimes it happens after changing resolution one or two times in succession, sometimes it takes ~10 changes to trigger the crash.

The crash is reproducible regardless if full-screen or windowed mode is used.  Also reproducible with the latest SDL2 snapshot build for Linux.

### Save file

No save file needed.  Just start the game and try to change resolution back and forth.

**Comment by oleg-derevenetz** [comment]
All these places work with SDL surface. Given the #4103, looks like a some Linux-specific SDL issue.

**Comment by a1exsh** [comment]
Just in case:
```
$ dpkg -l | grep libsdl2
ii  libsdl2-2.0-0:amd64                   2.0.14+dfsg2-3pureos1           amd64        Simple DirectMedia Layer
ii  libsdl2-dev:amd64                     2.0.14+dfsg2-3pureos1           amd64        Simple DirectMedia Layer development files
ii  libsdl2-image-2.0-0:amd64             2.0.5+dfsg1-2                   amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-image-dev:amd64               2.0.5+dfsg1-2                   amd64        Image loading library for Simple DirectMedia Layer 2, development files
ii  libsdl2-mixer-2.0-0:amd64             2.0.4+dfsg1-3                   amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-dev:amd64               2.0.4+dfsg1-3                   amd64        Mixer library for Simple DirectMedia Layer 2, development files
```

The distro is a Debian-derivative.

**Comment by oleg-derevenetz** [comment]
@a1exsh since you have the Linux system where all these issues are reproducible, you have all the cards in your hands to investigate this :)

**Comment by a1exsh** [comment]
> All these places work with SDL surface. Given the #4103, looks like a some Linux-specific SDL issue.

You are right, both issues are not reproducible on my other system (Ubuntu 20.10), with the following SDL versions:
```
$ dpkg -l | grep libsdl2
ii  libsdl2-2.0-0:amd64                        2.0.12+dfsg1-4                           amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:i386                         2.0.12+dfsg1-4                           i386         Simple DirectMedia Layer
ii  libsdl2-dev:amd64                          2.0.12+dfsg1-4                           amd64        Simple DirectMedia Layer development files
ii  libsdl2-image-2.0-0:amd64                  2.0.5+dfsg1-2                            amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-image-dev:amd64                    2.0.5+dfsg1-2                            amd64        Image loading library for Simple DirectMedia Layer 2, development files
ii  libsdl2-mixer-2.0-0:amd64                  2.0.4+dfsg1-2build1                      amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-dev:amd64                    2.0.4+dfsg1-2build1                      amd64        Mixer library for Simple DirectMedia Layer 2, development files
ii  libsdl2-ttf-2.0-0:amd64                    2.0.15+dfsg1-1                           amd64        TrueType Font library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-dev:amd64                      2.0.15+dfsg1-1                           amd64        TrueType Font library for Simple DirectMedia Layer 2, development files
```

**Comment by oleg-derevenetz** [comment]
@a1exsh doesn't the Linux system where issues are observed use musl instead of glibc? Or maybe some libraries are built with musl on that system?

**Comment by a1exsh** [comment]
@oleg-derevenetz interesting guess, but doesn't seem so.

I've now built the 3 sdl libs from source and both issues (this and #4103) are gone.  I've used the latest libsdl release, though, 2.0.16.  Will try with 2.0.14 to see if may be this particular version was buggy.

In the end, sorry for the noise, and thanks for debugging suggestions :)
