### ISSUE TITLE
Combat screen, Army order bar, the game crashes when the action bar goes over the edge of the screen and a hero flees or surrenders

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#5167]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the game crashes when the action bar goes over the edge of the screen and a hero flees or surrenders.

In fheroes2:

![Army order bar 004](https://user-images.githubusercontent.com/43583994/159983273-6efe9bf6-4f7e-4b0d-a497-8095fd0ed017.png)

### Save file

Here is the save file:
[Before full bar elemental 01.zip](https://github.com/ihhub/fheroes2/files/8344308/Before.full.bar.elemental.01.zip)

### Additional info

Version 0.9.13 5161

Related issue: https://github.com/ihhub/fheroes2/issues/5166.

**Comment by oleg-derevenetz** [comment]
Yeah, there is out-of-bounds write when trying to draw the part of the army order bar outside the screen:

```
    #0 0x10c706f85 in fheroes2::DrawLine(fheroes2::Image&, fheroes2::PointBase2D<int> const&, fheroes2::PointBase2D<int> const&, unsigned char, fheroes2::RectBase2D<int, int> const&) image.cpp:1475
    #1 0x10c708a40 in fheroes2::DrawRect(fheroes2::Image&, fheroes2::RectBase2D<int, int> const&, unsigned char) image.cpp:1510
    #2 0x10b198456 in Battle::ArmiesOrder::RedrawUnit(fheroes2::RectBase2D<int, int> const&, Battle::Unit const&, bool, bool, unsigned char, fheroes2::Image&) const battle_interface.cpp:878
    #3 0x10b19a125 in Battle::ArmiesOrder::Redraw(Battle::Unit const*, unsigned char, fheroes2::Image&) battle_interface.cpp:909
    #4 0x10b1a7cdb in Battle::Interface::RedrawPartialFinish() battle_interface.cpp:1123
    #5 0x10b1a78f1 in Battle::Interface::Redraw() battle_interface.cpp:1109
    #6 0x10b1ce097 in Battle::Interface::HumanTurn(Battle::Unit const&, Battle::Actions&) battle_interface.cpp:2278
    #7 0x10afe1047 in Battle::Arena::HumanTurn(Battle::Unit const&, Battle::Actions&) battle_arena.cpp:695
    #8 0x10afdf271 in Battle::Arena::TurnTroop(Battle::Unit*, Battle::Units const&) battle_arena.cpp:477
    #9 0x10afe87f0 in Battle::Arena::Turns() battle_arena.cpp:619
    #10 0x10b2beb16 in Battle::Loader(Army&, Army&, int) battle_main.cpp:225
    #11 0x10be3b49e in ActionToHeroes(Heroes&, int) heroes_action.cpp:721
    #12 0x10be2d704 in Heroes::Action(int, bool) heroes_action.cpp:333
    #13 0x10bf5fa50 in Heroes::MoveStep(Heroes&, int, bool) heroes_move.cpp:698
    #14 0x10bf603e9 in Heroes::MoveStep(bool) heroes_move.cpp:721
    #15 0x10bf681d5 in Heroes::Move(bool) heroes_move.cpp:1000
    #16 0x10bb1b0a3 in Interface::Basic::HumanTurn(bool) game_startgame.cpp:1038
    #17 0x10bb0470d in Interface::Basic::StartGame() game_startgame.cpp:647
    #18 0x10bb014d1 in Game::StartGame() game_startgame.cpp:89
    #19 0x10ba98db1 in Game::mainGameLoop(bool) game_mainmenu.cpp:143
    #20 0x10b948346 in main fheroes2.cpp:274
    #21 0x1173fa4fd in start+0x1cd (dyld:x86_64+0x54fd)
```
